import React from "react";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { WithTheme, defaultTheme as theme } from "@/lib/theme";
import "@/lib/styles/globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <WithTheme theme={theme}>
          <AntdRegistry>{children}</AntdRegistry>
        </WithTheme>
      </body>
    </html>
  );
}
